# --- BASIC SETTINGS ---
resolution 0
use_graphics_for linux
hideui hints
showtools firmware

# --- ICONS & BACKGROUND ---
icons_dir themes/rEFInd-grayscale-minimal/icons
banner themes/rEFInd-grayscale-minimal/background.png
banner_scale fillscreen

# --- ICON SIZES ---
big_icon_size 192
small_icon_size 96

# --- FONT (branco com contorno preto; um por resolução, copiado pelo instalador) ---
font themes/rEFInd-grayscale-minimal/font.png

# --- SELECTION HIGHLIGHTS ---
selection_small themes/rEFInd-grayscale-minimal/selection_small.png
selection_big themes/rEFInd-grayscale-minimal/selection_big.png